## Numpy Mathematics

In [1]:
import numpy as np

Addition of Numpy Array

In [4]:
n1 = np.array([10,20])
n2 = np.array([30,40])
n3 = np.array([50,60])

In [5]:
# Sum of all element of numpy array
np.sum([n1,n2,n3])

210

In [6]:
# sum of column-wise element
np.sum([n1,n2,n3],axis=0)

array([ 90, 120])

In [7]:
# sum of row-wise element
np.sum([n1,n2,n3],axis=1)

array([ 30,  70, 110])

# Scalar Operation

In [8]:
n1 = np.array([10,20,30])

In [9]:
# basic addition
n1+1

array([11, 21, 31])

In [10]:
# basic multiplication
n1*2

array([20, 40, 60])

In [11]:
# basic substraction
n1-3

array([ 7, 17, 27])

In [12]:
# division
n1/10

array([1., 2., 3.])

In [15]:
# mean
np.mean(n1)

20.0

In [16]:
# median
np.median(n1)

20.0

In [17]:
# standard deviation
np.std(n1)

8.16496580927726