In [1]:
## Intro

In [2]:
import numpy as np

In [3]:
# 1-D array

In [4]:
n1 = np.array([1,2,3,4])
n1

array([1, 2, 3, 4])

In [5]:
#2-D array

In [6]:
n2 = np.array([[1,2,3],[4,7,8]])
n2

array([[1, 2, 3],
       [4, 7, 8]])

In [7]:
# initialize with zeros

In [8]:
n3 = np.zeros((2,4)) # (rows,columns)
n3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
# initialize with full array with particular number

In [10]:
n4 = np.full((2,4),10) # (rows,columns),num
n4

array([[10, 10, 10, 10],
       [10, 10, 10, 10]])

In [11]:
# initializing numpy array within a range
# np.arange(start,end,step) # end is exclusive

In [13]:
n5 = np.arange(11,21)
n5

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [16]:
n5 = np.arange(0,50,5) # as 50 is exclusive
n5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [17]:
# initializing numpy array with random array
# np.random.randint(starting,ending,count)

In [19]:
n6 = np.random.randint(1,100,5)
n6

array([75, 44, 96, 53, 21])

In [20]:
n6 = np.random.randint(1,50,11)
n6

array([29, 35,  8, 26, 37, 37, 41, 38, 29, 44, 10])