## Numpy matrix

In [1]:
import numpy as np

# Accessing particular rows and colummn

In [5]:
n1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
n1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
# Accessing rows
n1[0] # first row

array([1, 2, 3])

In [4]:
n1[1] # second row

array([4, 5, 6])

In [6]:
# accesing column
n1[:,1] # 2 column

array([2, 5, 8])

# matrix transpose

In [7]:
# interchanging rows and column
n1.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# matrix multiplication

In [10]:
n1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
n2 = np.array([[9,8,7],[6,5,4],[3,2,1]])

In [11]:
n1.dot(n2)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [12]:
n2.dot(n1)

array([[ 90, 114, 138],
       [ 54,  69,  84],
       [ 18,  24,  30]])

# numpy Save and Load

In [13]:
# save numpy array
n1 = np.array([10,20,30,40,50,60,70,80])
np.save("my_numpy",n1)

In [14]:
# Load numpy
n2 = np.load("my_numpy.npy")
n2 # print

array([10, 20, 30, 40, 50, 60, 70, 80])