# numpy operation

In [4]:
import numpy as np

# Numpy-Shape

In [5]:
#checking shape of Numpy Array
n1 = np.array([[1,2,3],[4,5,6]])
n1.shape


(2, 3)

In [6]:
# changing shape of numpy array
n1.shape=(3,2)
n1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
# Joining Numpy Arrays

In [12]:
n1 = np.array([1,2,3,4])
n2 = np.array([5,6,7,8])

# 1. vertical stack
# vstack()

In [13]:
np.vstack((n1,n2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
np.vstack((n2,n1))

array([[5, 6, 7, 8],
       [1, 2, 3, 4]])

# 2. horizontal stack
# hstack()

In [16]:
np.hstack((n1,n2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
np.hstack((n2,n1))

array([5, 6, 7, 8, 1, 2, 3, 4])

# 3. column stack
# column_stack()

In [19]:
np.column_stack((n1,n2))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [21]:
np.column_stack((n2,n1))

array([[5, 1],
       [6, 2],
       [7, 3],
       [8, 4]])

# Numpy Intersection and Difference

In [22]:
n1 = np.array([1,2,3,4,5,6])
n2 = np.array([5,6,7,8,9])

In [23]:
# Common elemnt between n1 and n2
np.intersect1d(n1,n2)

array([5, 6])

In [24]:
np.intersect1d(n2,n1)

array([5, 6])

In [26]:
#Element unique to n1
np.setdiff1d(n1,n2)

array([1, 2, 3, 4])

In [27]:
# Element unique to n2
np.setdiff1d(n2,n1)

array([7, 8, 9])